/**
 * Sports emoji mapping
 * Maps each sport to a relevant emoji icon
 */

export const SPORTS_EMOJI: Record<string, string> = {
  "Basketball": "🏀",
  "Tennis": "🎾",
  "Badminton": "🏸",
  "Soccer": "⚽",
  "Volleyball": "🏐",
  "Badminton Doubles": "🏸",
  "Pickleball": "🏸",
  "Squash": "🎾",
  "Baseball": "⚾",
  "Softball": "⚾",
  "Football": "🏈",
  "American Football": "🏈",
  "Rugby": "🏉",
  "Field Hockey": "🏑",
  "Ice Hockey": "🏒",
  "Lacrosse": "🏑",
  "Running": "🏃",
  "Jogging": "🏃",
  "Cycling": "🚴",
  "Mountain Biking": "🚴",
  "Swimming": "🏊",
  "Water Polo": "🏊",
  "Diving": "🤿",
  "Surfing": "🏄",
  "Skateboarding": "🛹",
  "Rock Climbing": "🧗",
  "Hiking": "🥾",
  "Trail Running": "🏃",
  "Boxing": "🥊",
  "Muay Thai": "🥊",
  "Kickboxing": "🥊",
  "Mixed Martial Arts": "🥊",
  "Wrestling": "🤼",
  "Judo": "🥋",
  "Karate": "🥋",
  "Taekwondo": "🥋",
  "Yoga": "🧘",
  "Pilates": "🧘",
  "CrossFit": "💪",
  "Weightlifting": "🏋️",
  "Strength Training": "💪",
  "Gymnastics": "🤸",
  "Parkour": "🤸",
  "Parkour Freerunning": "🤸",
  "Golf": "⛳",
  "Disc Golf": "⛳",
  "Table Tennis": "🏓",
  "Ping Pong": "🏓",
  "Handball": "🤾",
  "Racquetball": "🎾",
  "Cricket": "🏏",
  "Kabaddi": "🏃",
  "Ultimate Frisbee": "🥏",
  "Roller Skating": "🛼",
  "Roller Hockey": "🛼",
  "Ice Skating": "⛸️",
  "Speed Skating": "⛸️",
  "Figure Skating": "⛸️",
  "Rowing": "🚣",
  "Kayaking": "🚣",
  "Canoeing": "🚣",
  "Sailing": "⛵",
  "Stand Up Paddleboarding": "🏄",
  "Snowboarding": "🏂",
  "Skiing": "⛷️",
  "Cross Country Skiing": "⛷️",
  "Downhill Skiing": "⛷️",
  "Snowshoeing": "🥾",
  "Ice Climbing": "🧗",
  "Backcountry Skiing": "⛷️",
  "Dancing": "💃",
  "Ballet": "🩰",
  "Contemporary Dance": "💃",
  "Hip Hop Dance": "🎤",
  "Salsa Dancing": "💃",
  "Swing Dancing": "💃",
  "Cheerleading": "📣",
  "Bowling": "🎳",
  "Darts": "🎯",
  "Pool": "🎱",
  "Billiards": "🎱",
  "Snooker": "🎱",
};

export function getSportEmoji(sport: string): string {
  return SPORTS_EMOJI[sport] || "⚽"; // Default to soccer ball if sport not found
}
