/**
 * Comprehensive list of sports available in HopOn
 * Used across create event, profile, and discovery pages
 */

export const AVAILABLE_SPORTS = [
  "Basketball",
  "Tennis",
  "Badminton",
  "Soccer",
  "Volleyball",
  "Badminton Doubles",
  "Pickleball",
  "Squash",
  "Baseball",
  "Softball",
  "Football",
  "American Football",
  "Rugby",
  "Field Hockey",
  "Ice Hockey",
  "Lacrosse",
  "Running",
  "Jogging",
  "Cycling",
  "Mountain Biking",
  "Swimming",
  "Water Polo",
  "Diving",
  "Surfing",
  "Skateboarding",
  "Rock Climbing",
  "Hiking",
  "Trail Running",
  "Boxing",
  "Muay Thai",
  "Kickboxing",
  "Mixed Martial Arts",
  "Wrestling",
  "Judo",
  "Karate",
  "Taekwondo",
  "Yoga",
  "Pilates",
  "CrossFit",
  "Weightlifting",
  "Strength Training",
  "Gymnastics",
  "Parkour",
  "Parkour Freerunning",
  "Golf",
  "Disc Golf",
  "Table Tennis",
  "Ping Pong",
  "Handball",
  "Racquetball",
  "Cricket",
  "Kabaddi",
  "Ultimate Frisbee",
  "Roller Skating",
  "Roller Hockey",
  "Ice Skating",
  "Speed Skating",
  "Figure Skating",
  "Rowing",
  "Kayaking",
  "Canoeing",
  "Sailing",
  "Stand Up Paddleboarding",
  "Skateboarding",
  "Snowboarding",
  "Skiing",
  "Cross Country Skiing",
  "Downhill Skiing",
  "Snowshoeing",
  "Ice Climbing",
  "Backcountry Skiing",
  "Dancing",
  "Ballet",
  "Contemporary Dance",
  "Hip Hop Dance",
  "Salsa Dancing",
  "Swing Dancing",
  "Cheerleading",
  "Bowling",
  "Darts",
  "Pool",
  "Billiards",
  "Snooker",
].sort();
